window.__SAMA_DATA__ = {
  categories: [
    {
    id: "phones",
      nameAr: "الجوالات",
      icon: "smartphone",
      color: "#1B8EF8",
    bgColor: "#EBF3FE",
    hasSubcategories: true,
    subcategories: [
      { id: "iphone", nameAr: "آيفون" },
      { id: "samsung", nameAr: "سامسونج" },
      { id: "huawei", nameAr: "هواوي" },
    ],
    },
    {
    id: "electronics",
      nameAr: "إلكترونيات",
      icon: "tv",
      color: "#8B5CF6",
    bgColor: "#EDE9FE",
    hasSubcategories: true,
    subcategories: [
      { id: "tablets", nameAr: "أجهزة لوحية" },
      { id: "wearables", nameAr: "ساعات ذكية" },
    ],
    },
    {
    id: "electrical",
      nameAr: "الكهرباء",
      icon: "zap",
      color: "#F59E0B",
    bgColor: "#FEF3C7",
    hasSubcategories: true,
    subcategories: [
      { id: "chargers", nameAr: "شواحن" },
      { id: "cables", nameAr: "كيابل" },
    ],
    },
    {
    id: "accessories",
      nameAr: "الإكسسوارات",
      icon: "headphones",
      color: "#EC4899",
    bgColor: "#FCE7F3",
    hasSubcategories: true,
    subcategories: [
      { id: "earphones", nameAr: "سماعات" },
      { id: "cases", nameAr: "أغطية وحمايات" },
    ],
    },
    {
    id: "computers",
      nameAr: "الكمبيوتر وملحقاته",
      icon: "monitor",
      color: "#10B981",
    bgColor: "#D1FAE5",
    hasSubcategories: true,
    subcategories: [
      { id: "laptops", nameAr: "لابتوبات" },
      { id: "peripherals", nameAr: "ملحقات كمبيوتر" },
    ],
    },
    {
    id: "solar",
      nameAr: "الطاقة الشمسية",
      icon: "sun",
      color: "#F97316",
    bgColor: "#FFEDD5",
    hasSubcategories: true,
    subcategories: [
      { id: "panels", nameAr: "ألواح شمسية" },
      { id: "inverters", nameAr: "انفرترات ومنظمات" },
    ],
    },
    {
      id: "spare-parts",
      nameAr: "قطع الغيار",
      icon: "tool",
      color: "#EF4444",
      bgColor: "#FEE2E2",
      hasSubcategories: true,
      subcategories: [
        {
          id: "parts",
          nameAr: "القطع",
        },
        {
          id: "programming",
          nameAr: "البرمجة والتفعيل",
        },
      ],
    },
    {
      id: "our-work",
      nameAr: "أعمالنا",
      icon: "star",
      color: "#1ABC9C",
      bgColor: "#D1FAE5",
    },
  ],
  products: [
    {
      id: "p1",
      nameAr: "آيفون 15 برو ماكس",
      descriptionAr: "هاتف آبل الرائد بشاشة 6.7 بوصة وكاميرا 48 ميجابكسل",
      price: 1800,
      categoryId: "phones",
      subcategoryId: "iphone",
      inStock: true,
      specs: "256GB | تيتانيوم | iOS 17",
      createdAt: "2026-05-02T17:48:30.738Z",
    },
    {
      id: "p2",
      nameAr: "سامسونج S24 الترا",
      descriptionAr: "هاتف سامسونج الفلاجشيب مع قلم S Pen مدمج",
      price: 1650,
      categoryId: "phones",
      subcategoryId: "samsung",
      inStock: true,
      specs: "512GB | تيتانيوم أسود | Android 14",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p3",
      nameAr: "هواوي P60 برو",
      descriptionAr: "هاتف بكاميرا لايكا احترافية وبطارية طويلة الأمد",
      price: 1100,
      categoryId: "phones",
      subcategoryId: "huawei",
      inStock: true,
      specs: "256GB | أسود | HarmonyOS",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p4",
      nameAr: "آيباد برو 12.9",
      descriptionAr: "الجهاز اللوحي الأقوى من آبل بشريحة M2",
      price: 1400,
      categoryId: "electronics",
      subcategoryId: "tablets",
      inStock: true,
      specs: "256GB | WiFi + Cellular | 12.9 بوصة",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p5",
      nameAr: "ساعة آبل الإصدار 9",
      descriptionAr: "ساعة ذكية بمستشعرات صحية متقدمة",
      price: 450,
      categoryId: "electronics",
      subcategoryId: "wearables",
      inStock: true,
      specs: "45mm | ألومنيوم | GPS",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p6",
      nameAr: "كيبل شحن سريع USB-C",
      descriptionAr: "كيبل شحن سريع 65W متوافق مع جميع الأجهزة",
      price: 25,
      categoryId: "electrical",
      subcategoryId: "cables",
      inStock: true,
      specs: "طول 2 متر | 65W PD",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p7",
      nameAr: "شاحن سريع 65W GaN",
      descriptionAr: "شاحن جداري متعدد المنافذ بتقنية GaN",
      price: 85,
      categoryId: "electrical",
      subcategoryId: "chargers",
      inStock: true,
      specs: "3 منافذ USB-C | 1 USB-A | 65W",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p8",
      nameAr: "سماعات AirPods برو 2",
      descriptionAr: "سماعات لاسلكية بإلغاء الضجيج الفعّال",
      price: 350,
      categoryId: "accessories",
      subcategoryId: "earphones",
      inStock: true,
      specs: "إلغاء ضجيج | ANC | H2 Chip",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p9",
      nameAr: "كفر آيفون 15 برو",
      descriptionAr: "غطاء حماية عسكري مضاد للصدمات",
      price: 45,
      categoryId: "accessories",
      subcategoryId: "cases",
      inStock: true,
      specs: "MagSafe | حماية مستوى عسكري",
      createdAt: "2026-05-02T17:48:30.760Z",
    },
    {
      id: "p10",
      nameAr: "لابتوب ماك بوك برو 14",
      descriptionAr: "لابتوب آبل بشريحة M3 Pro للمحترفين",
      price: 2800,
      categoryId: "computers",
      subcategoryId: "laptops",
      inStock: true,
      specs: "M3 Pro | 18GB RAM | 512GB SSD",
      createdAt: "2026-05-02T17:48:30.761Z",
    },
    {
      id: "p11",
      nameAr: "لوح شمسي 400 واط",
      descriptionAr: "لوح شمسي أحادي البلورة بكفاءة عالية",
      price: 320,
      categoryId: "solar",
      subcategoryId: "panels",
      inStock: true,
      specs: "400W | أحادي البلورة | ضمان 25 سنة",
      createdAt: "2026-05-02T17:48:30.761Z",
    },
    {
      id: "p12",
      nameAr: "شاشة آيفون 13 أصلية",
      descriptionAr: "شاشة OLED أصلية مع مجموعة الإصلاح الكاملة",
      price: 180,
      categoryId: "spare-parts",
      subcategoryId: "parts",
      inStock: true,
      specs: "OLED | أصلية | تشمل أدوات التركيب",
      createdAt: "2026-05-02T17:48:30.761Z",
    },
    {
      id: "p13",
      nameAr: "بطارية سامسونج S21 أصلية",
      descriptionAr: "بطارية أصلية بسعة 4000mAh",
      price: 65,
      categoryId: "spare-parts",
      subcategoryId: "parts",
      inStock: true,
      specs: "4000mAh | ضمان 6 أشهر",
      createdAt: "2026-05-02T17:48:30.761Z",
    },
    {
      id: "p14",
      nameAr: "اشتراك سيرفر إزهاري",
      descriptionAr: "اشتراك سنوي في سيرفر الإزهاري لفك قفل الهواتف",
      price: 150,
      categoryId: "spare-parts",
      subcategoryId: "programming",
      inStock: true,
      specs: "اشتراك سنوي | جميع الماركات",
      createdAt: "2026-05-02T17:48:30.761Z",
    },
    {
      id: "p15",
      nameAr: "بوكس Sigma - للسامسونج",
      descriptionAr: "بوكس برمجة الهواتف سامسونج مع الكيبلات",
      price: 280,
      categoryId: "spare-parts",
      subcategoryId: "programming",
      inStock: true,
      specs: "يدعم سامسونج | مع 30 كيبل",
      createdAt: "2026-05-02T17:48:30.761Z",
    },
  ],
  whatsappNumber: "967783454544",
  workItems: [
    {
      id: "w1",
      titleAr: "إصلاح شاشة آيفون 14 برو",
      descriptionAr: "تم استبدال الشاشة المكسورة بشاشة OLED أصلية",
      type: "maintenance",
      date: "2024-12-01",
    },
    {
      id: "w2",
      titleAr: "فك قفل سامسونج S23",
      descriptionAr: "تم فك القفل عبر سيرفر الإزهاري بنجاح",
      type: "programming",
      date: "2024-12-05",
    },
    {
      id: "w3",
      titleAr: "تركيب لوح شمسي للمنزل",
      descriptionAr: "تم تركيب نظام طاقة شمسية 2000 واط لأحد العملاء",
      type: "other",
      date: "2024-12-10",
    },
  ],
};

var accessoriesCategory = window.__SAMA_DATA__.categories.find(function (category) {
  return category.id === "accessories";
});

if (accessoriesCategory) {
  accessoriesCategory.nameAr = "الملحقات";
}
